<?php
class Config_Pay{
	public static $pay_type = array(
		1 => array(
			"pay_cat" => 4,
			"code" => "alipay",
			"name" => "支付宝充值",
			"icon" => "/static/img/PayCenter/alipay.png",
			"trade_rat" => 1,
			"sort" => 1,
		),
		2 => array(
			"pay_cat" => 1,
			"code" => "yeepay",
			"name" => "银行卡（易宝）充值",
			"icon" => "/static/img/PayCenter/bankcard.png",
			"trade_rat" => 1,
			"sort" => 2,
		),
		3 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "骏网一卡通（易宝）支付",
			"bank_id" => "JUNNET-NET",
			"icon" => "/static/img/PayCenter/One-Card.png",
			"trade_rat" => 0.8,
			"sort" => 3,
		),
		4 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "神州行（易宝）支付",
			"bank_id" => "SZX-NET",
			"icon" => "/static/img/PayCenter/Easyown.png",
			"trade_rat" => 0.9,
			"sort" => 4,
		),
		5 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "联通卡（易宝）支付",
			"bank_id" => "UNICOM-NET",
			"icon" => "/static/img/PayCenter/CHINAUNICOM.png",
			"trade_rat" => 0.9,
			"sort" => 5,
		),
		6 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "电信卡（易宝）支付",
			"bank_id" => "TELECOM-NET",
			"icon" => "/static/img/PayCenter/telecom.png",
			"trade_rat" => 0.9,
			"sort" => 6,
		),
		7 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "征途卡（易宝）支付",
			"bank_id" => "ZHENGTU-NET",
			"icon" => "/static/img/PayCenter/journey.png",
			"trade_rat" => 0.8,
			"sort" => 7,
		),
		8 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "盛大卡（易宝）支付",
			"bank_id" => "SNDACARD-NET",
			"icon" => "/static/img/PayCenter/grand.png",
			"trade_rat" => 0.8,
			"sort" => 8,
		),
		9 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "网易卡（易宝）支付",
			"bank_id" => "NETEASE-NET",
			"icon" => "/static/img/PayCenter/Netease.png",
			"trade_rat" => 0.8,
			"sort" => 9,
		),
		10 => array(
			"pay_cat" => 2,
			"code" => "yeepay",
			"name" => "天下一卡通支付",
			"bank_id" => "TIANXIA-NET",
			"icon" => "/static/img/PayCenter/sky.png",
			"trade_rat" => 0.8,
			"sort" => 10,
		),
		11 => array(
			"pay_cat" => 3,
			"code" => "platform",
			"name" => "平台币支付",
			"icon" => "/static/img/PayCenter/platform.png",
			"trade_rat" => 1,
			"sort" => 11,
		),
	);
}